### ISSUE TITLE
action: golint

### ISSUE THREAD

**Issue by sjkaliski** [sjkaliski/go-github-actions#1]
Add support for [`golint`](https://github.com/golang/lint). E.g.

```hcl
action "go-lint" {
  uses    = "sjkaliski/go-github-actions/lint@v0.1.0"
  needs   = "previous-action"
  secrets = ["GITHUB_TOKEN"]

  env {
    GO_WORKING_DIR = "./path/to/go/files"
  }
}
```

**Comment by GregTheGreek** [comment]
What's the purpose of this? Could you add more descriptions to help contributers :)

**Comment by sjkaliski** [comment]
@GregTheGreek 👋

I'd like to replicate the functionality of https://github.com/sjkaliski/go-github-actions/tree/master/fmt for [golint](https://github.com/golang/lint).
