### ISSUE TITLE
Could not resolve host: null

### ISSUE THREAD

**Issue by steebchen** [sjkaliski/go-github-actions#12]
I have a single main.go in a folder go, but it fails with a curl error when fmt reports files:
```
go/main.go
curl: (6) Could not resolve host: null

### FAILED go fmt 23:29:39Z (15.78s)
```

main.workflow:
```hcl
workflow "Go linter" {
  on = "push"
  resolves = ["go fmt"]
}

action "go fmt" {
  uses = "sjkaliski/go-github-actions/fmt@v0.3.0"
  secrets = ["GITHUB_TOKEN"]
  env = {
    GO_WORKING_DIR = "."
  }
}
```

Any idea what could be wrong? I also tried without the env variable and with v0.2.0

**Comment by sjkaliski** [comment]
@steebchen thanks for sharing! I was able to reproduce your issue.

It seems the issue has to do with the event that triggers the workflow, in this case `push`. By modifying the `workflow` to trigger on `pull_request`, the issue goes away...

```hcl
workflow "Terraform - API" {
  on = "pull_request"
  resolves = ["go fmt"]
}
```

The action is designed to post a helpful comment to the PR when `go fmt` fails. However, if the event triggering the action is `push` it will not contain `pull_request.comments_url` which the action [depends on](https://github.com/sjkaliski/go-github-actions/blob/master/fmt/entrypoint.sh#L42) to post back the comment.

Adding a check for non-empty `COMMENTS_URL` before making the request should do the trick.

**Comment by steebchen** [comment]
Ah well, that makes sense. Thanks for the info!

**Comment by steebchen** [comment]
It would be also good to add the info to the readme.
