### ISSUE TITLE
Actions should check event that triggered them

### ISSUE THREAD

**Issue by jcmuller** [sjkaliski/go-github-actions#18]
This actions work very nicely! The README should mention that they expect to be triggered on `pull_request` events. Maybe the code should also check for that and blow up if it's not the right event.

**Comment by sjkaliski** [comment]
@jcmuller good call! Let's definitely update the main README and the action READMEs to look something like:

```hcl
workflow "Go" {
  on = "pull_request"
  resolves = ["gofmt"]
}

action "gofmt" {
  uses    = "sjkaliski/go-github-actions/fmt@v0.4.0"
  secrets = ["GITHUB_TOKEN"]

  env {
    GO_WORKING_DIR = "./path/to/go/files"
    GO_IGNORE_DIRS = "./vendor"
  }
}
```

Currently, if the triggering event is not `pull_request` the action will still run, but it will not attempt to post a comment back w/ results. That seems fine IMO, but perhaps worth calling out.

**Comment by jcmuller** [comment]
Thanks!
