### ISSUE TITLE
Ability to ignore specific (e.g. vendor) directories.

### ISSUE THREAD

**Issue by joshdk** [sjkaliski/go-github-actions#6]
A lot of projects will commit their vendored dependencies, or resolve them in CI. A lot of the time, this vendored code is not properly formatted/vetted/etc.

The ability to ignore directories like these might be useful for a broader audience. Usage could potentially look like this:

```hcl
action "gofmt" {
  uses = "sjkaliski/go-github-actions/fmt@..."
  ...

  env {
    GO_IGNORE_DIRS = "vendor,internal,some/other/pkg"
  }
}
```

Cheers!

**Comment by sjkaliski** [comment]
Definitely agree!

**Comment by sjkaliski** [comment]
Just published v0.2.0 with support for golint. @acburdine's implementation there included a `GO_LINT_PATHS` env var, defaulting to `./...`. I think a similar implementation can be done here

```hcl
action "gofmt" {
  uses = "sjkaliski/go-github-actions/fmt@..."
  ...

  env {
    GO_FMT_PATHS = "./ ./bar/... ./foo/..."
  }
}
```

Thoughts @joshdk?

**Comment by leosunmo** [comment]
Wrote up a quick PR for this that I use in a project. Give it a test and leave me some feedback!

**Comment by sjkaliski** [comment]
Hey @leosunmo thanks for doing that! Will take a look.

**Comment by sjkaliski** [comment]
Closed via https://github.com/sjkaliski/go-github-actions/pull/15
